version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      day: "monday"
    labels:
      - skip-changelog
      - dependencies
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      day: "monday"
    labels:
      - skip-changelog
      - dependencies
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      day: "monday"
    labels:
      - skip-changelog
      - dependencies
    open-pull-requests-limit: 10
